development:
  name: Development
  task: 'task development...'

compress:
  name: Compress
  task: 'task compress'

code-test:
  name: Mocha Test
  task: 'task code-test'

code-clints:
  name: Clints
  task: 'code-clints'

new-project:
  name: Create Project
  task: 'new-project'

new-react-redux-project:
  name: Create React & Redux Project
  task: 'new-react-redux-project'

new-react-native-redux-project:
  name: Create React-Native & Reudx Project
  task: 'new-react-native-redux-project'

new-page:
  name: Create Page
  task: 'new-page'

react-react-page:
  name: Create React Page
  task: 'react-react-page'

new-componentt:
  name: Create Componen
  task: 'new-component'

publish: 
  name: Publish Git
  task: 'publish branch to origin responstory'

upgrade:
  name: Upgrade
  task: 'upgrade'
