start:
  name: Development
  task: task development...
  command-config:
    command: start [port]
    description:
      - Start running server
    # option:
    #   - -P, --port <n>
    #   - server port, default port 3000; 

pack:
  name: Packing
  task: task compress
  child-question:
    type: list
    name: pack
    message: 'Select Packing Env:'
    choices:
      - name: Develop
        value: develop
      - name: Test
        value: test
      - name: Pre
        value: pre
      - name: Release
        value: release
  command-config:
    command: pack <env>
    description:
      - your des pack code
    option:
      - -d, --dev <string>
      - pack develop env
    option-2:
      - -t, --test <string>
      - pack test env
    option-3:
      - -p, --pre <string>
      - pack pre env
    option-4:
      - -r, --release <string>
      - pack release env

test:
  name: Testing Code
  task: task code-test
  command-config:
    command: test
    description:
      - your des
    # option:
    #   - -nk, --nknow <string>
    #   - server port, default port 3000

lint:
  name: Lint
  task: code-clints
  command-config:
    command: lint
    description:
      - your des
    # option:
    #   - -nk, --nknow <string>
    #   - server port, default port 3000

project:
  name:  Creating Porject
  task: new-project
  child-question:
    type: list
    name: project
    message: 'Select Porject Mode:'
    choices:
      - name: Normal
        value: normal
      - name: React
        value: react
      - name: React-Redux
        value: react-redux
      - name: React-Native
        value: react-native
  command-config:
    command: project <name>
    description:
      - create project.[mode] { arguments -> normal | react | react-redux | react-native> }; Nothing or error argument will create Normal Project.
    option:
      - -r, --react [string]
      - create project with react
    option-2:
      - -d, --react-redux
      - create project with react and redux
    option-3:
      - -n, --react-native
      - create project with react-native and redux

page: 
  name: Creating Page
  task: new-page
  child-question:
    type: list
    name: page
    message: 'Select Page Mode:'
    configChild: &configChild
      name: Input Page Name
      type: input
      message: 'Input Name <Multi-name use empty key-press>:'
    choices:
      - name: Normal
        value: 
          child-question:
            <<: *configChild
      - name: React
        value: 
          child-question:
            <<: *configChild

  command-config:
    command: page <name> [otherPageNames...]
    description:
      - create page. default normal page [mode] {arguments -> normal | react}; Nothing or error argument will crate Normal Page.
    option:
      - -r, --react <mode>
      - create page with react
    # option-2:
    #   - -n, --normal <mode>
    #   - create normal page

component:
  name: Creating Component
  task: new-component
  child-question:
    name: 'Input Component Name'
    type: input
    message: 'Input Name <Multi-name use empty key-press>:'
  command-config:
    command: component <name> [otherComponentNames...]
    description:
      - create react component.

publish: 
  name: Publish Git
  task: publish branch to origin responstory
  command-config:
    command: publish [env-git]
    description:
      - push code to origin responstory

upgrade:
  name: Upgrade
  task: upgrade
  command-config:
    command: upgrade
    description:
      - upgrade smart version
