start:
  name: Development
  task: task development...
  command-config:
    command: start [port]
    description:
      - start running server for developing
    option:
      - -P, --port <n>
      - server port, default port 3000; 

pack:
  name: Packing
  task: task compress
  child-interactive:
    type: list
    name: pack
    message: 'Select Packing Env:'
    choices:
      - name: Develop
        value: develop
      - name: Test
        value: test
      - name: Pre
        value: pre
      - name: Release
        value: release
  command-config:
    command: Compress [env]
    description:
      - your des pack code
    option:
      - -nk, --nknow <string>
      - server port, default port 3000

test:
  name: Testing Code
  task: task code-test
  command-config:
    command: test
    description:
      - your des
    option:
      - -nk, --nknow <string>
      - server port, default port 3000

lint:
  name: Lint
  task: code-clints
  command-config:
    command: lint
    description:
      - your des
    option:
      - -nk, --nknow <string>
      - server port, default port 3000

project:
  name:  Creating Porject
  task: new-project
  child-interactive:
    type: list
    name: project
    message: 'Select Porject Mode:'
    choices:
      - name: Normal
        value: normal
      - name: React
        value: react
      - name: React-Redux
        value: react-redux
      - name: React-Native
        value: react-native
  command-config:
    command: project [mode]
    description:
      - create project.<argument:mode -> normal | react | react & redux | react-native>; default normal project [moode]
    option:
      - -re, --react <string>
      - create project with react
    option-2:
      - -rd, --react-redux
      - create project with react and redux
    option-3:
      - -ren, --react-native
      - create project with react-native and redux

page: 
  name: Creating Page
  task: new-page
  child-interactive:
    type: list
    name: page
    message: 'Select Page Mode:'
    choices:
      - name: Normal
        value: normal
      - name: React
        value: react
  command-config:
    command: page [mode]
    description:
      - create page. default normal page [mode]
    option:
      - -re, --react <string>
      - create page with react

component:
  name: Creating Component
  task: new-component
  command-config:
    command: component
    description:
      - create react component.

publish: 
  name: Publish Git
  task: publish branch to origin responstory
  command-config:
    command: publish [env-git]
    description:
      - push code to origin responstory

upgrade:
  name: Upgrade
  task: upgrade
  command-config:
    command: upgrade
    description:
      - upgrade smart version
