port: 3030
# <Number> for debug

host: 0.0.0.0
# <String> for debug

clientDir: src
# working directory

staticDir: dist
# compiled files to disk where you want it to be emitted to

vendors: null
# <Array>

pages: pages
# <String | Object> entry point for App
# String for a Single Page Application
# Object for multi Page Application
  
